name: asserest
description: Console application for verifing provided address can be access on client network
publish_to: 'none'
version: 1.0.0-beta.1
repository: https://github.com/rk0cc/asserest
environment:
  sdk: '>2.18.999 <4.0.0'
dependencies:
  path: ^1.8.0
  http: ^0.13.5
  yaml: ^3.1.1
  ftpconnect: ^2.0.5
  meta: ^1.8.0
  quiver: ^3.2.1
  args: ^2.3.2
  ansicolor: ^2.0.1
  async_task: ^1.0.20
  sprintf: ^7.0.0
dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
funding:
  - https://github.com/sponsors/rk0cc
